# Numpy

# 參考資料:
https://numpy.org/devdocs/user/quickstart.html →英文的
    
https://www.numpy.org.cn/  →中文的

In [7]:
#建立陣列
import numpy as np

a = np.array([1,2,3])
print(a) 
print(a.ndim)  #軸(axis)數量
print(a.shape) #陣列的維度(n,m)
print(a.size)  #n*m
print(a.dtype) #array物件的元素類型

b = np.array([[1,2,3],[4,5,6]])
print(b)
print(b.ndim)
print(b.shape)
print(b.size)
print(b.dtype)

c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)
print(c.ndim)
print(c.shape)
print(c.size)
print(c.dtype)

[1 2 3]
1
(3,)
3
int32
[[1 2 3]
 [4 5 6]]
2
(2, 3)
6
int32
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3
(2, 2, 2)
8
int32


In [16]:
#指定陣列的資料型態
import numpy as np
a = np.array([1,2,3,4])
print(a)
print(a.dtype)
a = np.array([1,2,3,4],np.int64) #改成int64
print(a)
print(a.dtype)
a = np.array([1,2,3,4],dtype=float) #改成float64
print(a)
print(a.dtype)
a = np.array([1,2,3,4],dtype=complex) #改成complex複數
print(a.dtype)
b = np.array(a,dtype=float,copy=True) #複製a陣列
print(b)
print(b.dtype)

[1 2 3 4]
int32
[1 2 3 4]
int64
[1. 2. 3. 4.]
float64
[1.+0.j 2.+0.j 3.+0.j 4.+0.j]
complex128
[1. 2. 3. 4.]
float64


d:\anaconda3\envs\anaconda_project\lib\site-packages\ipykernel_launcher.py:15: ComplexWarning: Casting complex values to real discards the imaginary part
  from ipykernel import kernelapp as app


In [21]:
#自訂結構型態
import numpy as np
#int8,int16,int32,int64 可用'i1','i2','i4','i8' 代替
#float16,float32,float64 可用'f1','f2','f4' 代替

dt = np.dtype('f2')
print(dt)

people = np.dtype([('name','S20'),('height','i4'),('weight','f2')])

a = np.array([('Amy',156,50),('Bob',175,72)],dtype=people)
print(a)
print(a['name']) #b' ' byte string 字節字面常數
print(a['height'])
print(a['weight'])

float16
[(b'Amy', 156, 50.) (b'Bob', 175, 72.)]
[b'Amy' b'Bob']
[156 175]
[50. 72.]


In [27]:
#變換陣列的形狀排列與維度
import numpy as np
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

a_2d = a.reshape(3,4) #變成3*4
print(a_2d)
print('\n')
a_3d = a.reshape(3,2,2)
print(a_3d)
print('\n')
a_2d_col = a.reshape(3,4,order ='F') #陣列在記憶體的排序 C(按列) F(按行) A(原順序) K(元素在記憶體出現的順序)
print(a_2d_col)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]


In [28]:
#從數值範圍建立陣列 numpy.arange(start,stop,step,dtype)
import numpy as np
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

a = np.arange(12)
print(a)

a = np.arange(12).reshape(4,3)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [29]:
#等差數列與等比數列 
#np.linspace(start,stop,num=50,endpoint=True,retstep=False)
#np.logspace(start,stop,num=50,endpoint=True,base=10.0)

import numpy as np
a = np.linspace(10,20,5,endpoint=False)
print(a)

b = np.linspace(0,2,9).reshape(3,3)
print(b)

c = np.logspace(0,9,10,base=2,dtype='i4').reshape(2,5) #基底2的次方,在0-9產出十個型態為'i4',2*5的陣列
print(c)

[10. 12. 14. 16. 18.]
[[0.   0.25 0.5 ]
 [0.75 1.   1.25]
 [1.5  1.75 2.  ]]
[[  1   2   4   8  16]
 [ 32  64 128 256 512]]


In [35]:
#陣列填值
import numpy as np
a = np.zeros([2,3])  #2*3填入0的矩陣
print(a)

b = np.ones([2,3])   #2*3填入1的矩陣
print(b)

c = np.array([[1,2,3],[4,5,6]])
c0 = np.zeros_like(c)  #像c一樣，填入0的矩陣
print(c0)
c1 = np.ones_like(c)
print(c1)

d =np.random.random((2,3)) #第一個random 隨機產生陣列內的機率值
print(d)

e = np.empty([2,2]) #創建一個指定形狀（shape） (2,2)、數據類型（dtype）且未初始化的數組
print(e)

e1 = np.empty_like(c)
print(e1)

f = np.eye(3,dtype=int)
print(f)
f1 = np.eye(3,k=1) #偏移+1向右,-1向左
print(f1)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]]
[[0.11299291 0.58672572 0.02259892]
 [0.6456136  0.99273752 0.11405951]]
[[4.9e-324 9.9e-324]
 [1.5e-323 2.0e-323]]
[[1 1 1]
 [1 1 1]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


In [37]:
#陣列切片
import numpy as np
a = np.arange(6) #一維陣列
print(a[2:-1])
print(a[::2]) #2是間距
print('')

a = np.array([[11,12,13],[23,24,25],[34,35,36]]) #二維陣列
print(a)
print('')

print(a[1]) #index=1
print(a[1:])
print(a[1][1:])
print('')

print(a[...,1])#...代表省略
print(a[1,...])
print(a[...,1:])

[2 3 4]
[0 2 4]

[[11 12 13]
 [23 24 25]
 [34 35 36]]

[23 24 25]
[[23 24 25]
 [34 35 36]]
[24 25]

[12 24 35]
[23 24 25]
[[12 13]
 [24 25]
 [35 36]]


In [40]:
#多維陣列的索引
#Numpy 二維陣列的索引
import numpy as np
a = np.arange(0,36).reshape(6,6)
print(a)

print(a[4,5])
print(a[4,-1])
print('')

print(a[3,1:4])
print('')

print(a[:3,3:])
print('')

print(a[2,:])
print('')

print(a[:,3]) #全部的列,index=3 ,理論上是行向量，但Numpy輸出是列向量
print('')

print(a[:,::2]) #全部的列,index以2的級距
print('')

print(a[::2,::3]) #列以2的級距,行以3的級距

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
29
29

[19 20 21]

[[ 3  4  5]
 [ 9 10 11]
 [15 16 17]]

[12 13 14 15 16 17]

[ 3  9 15 21 27 33]

[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]
 [18 20 22]
 [24 26 28]
 [30 32 34]]

[[ 0  3]
 [12 15]
 [24 27]]


In [41]:
#Numpy 三維陣列的索引
import numpy as np
a = np.arange(16).reshape(2,2,4)
print(a)
print('')

print(a[0])
print('')

print(a[0,:,1:3])
print('')

print(a[0,1]) #陣列的索引
print('')

print(a[0][1])#切片擷取
print('')

print(a[0,1,2]) #陣列索引
print('')

print(a[0][1][2]) #切片擷取
print('')

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]

[[0 1 2 3]
 [4 5 6 7]]

[[1 2]
 [5 6]]

[4 5 6 7]

[4 5 6 7]

6

6



In [42]:
#陣列索引的其他方式
import numpy as np

x = np.arange(25).reshape(5,5)
print(x)
print('')

print(x[[0,1,2],[0,1,0]])
print('')

print(x[[2,4]]) #row取2及4
print('')

print(x[x > 20]) #布林索引
print(x[x % 2 == 0])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

[ 0  6 10]

[[10 11 12 13 14]
 [20 21 22 23 24]]

[21 22 23 24]
[ 0  2  4  6  8 10 12 14 16 18 20 22 24]


In [44]:
#陣列與共用記憶體
import numpy as np

a = np.arange(7)
print(a)

b = a[2:6]
print(b)

c = a[2:6].copy()

print(np.may_share_memory(a,b)) #檢查a,b是否在同個記憶體
print(np.may_share_memory(a,c))

b[0] = 20
print(b)
print(a) #發現a也改變了

[0 1 2 3 4 5 6]
[2 3 4 5]
True
False
[20  3  4  5]
[ 0  1 20  3  4  5  6]


In [45]:
#廣播(Broadcast):是numpy對不同形狀(shape)的陣列進行陣列計算的方式
 #形狀相同時，a*b就是兩陣列對應位置的元素相乘
 #形狀不同時，將自動觸發廣播機制

import numpy as np
a = np.array([[1,2,3,4],[4,5,6,7]])
b = np.random.randint(1,3,8).reshape(2,4) #隨機產生1-3整數8筆

print(a)
print(b)
print('')

print(a*b)
print('')

c = np.array([1,2]).reshape(2,1) #乘法廣播
print(c)
print('')

print(a*c)
print('')

d = np.array([1,1,1,1]) #加法廣播
print(a+d)

[[1 2 3 4]
 [4 5 6 7]]
[[2 1 1 1]
 [2 1 2 2]]

[[ 2  2  3  4]
 [ 8  5 12 14]]

[[1]
 [2]]

[[ 1  2  3  4]
 [ 8 10 12 14]]

[[2 3 4 5]
 [5 6 7 8]]


In [47]:
#矩陣計算
import numpy as np
a = np.arange(6).reshape(2,3)
print(a)
print('')

print(a+5) #每個位子+5
print('')

b = np.ones(6,dtype = int).reshape(2,3)
print(b)

print(a+2*b) #矩陣加法與純量乘法

[[0 1 2]
 [3 4 5]]

[[ 5  6  7]
 [ 8  9 10]]

[[1 1 1]
 [1 1 1]]
[[2 3 4]
 [5 6 7]]


In [48]:
import numpy as np
a = np.arange(6).reshape(2,3)
print(a)
print('')

b = np.arange(6).reshape(3,2)
print(b)
print('')

c = np.dot(a,b) #矩陣內積
print(c)
print('')

print(c.T) #矩陣轉置

[[0 1 2]
 [3 4 5]]

[[0 1]
 [2 3]
 [4 5]]

[[10 13]
 [28 40]]

[[10 28]
 [13 40]]


In [49]:
#內建函數
import numpy as np
a = np.arange(6)

print(a.sum())
print('')

print(a.std())
print('')

print(a.mean())
print('')

print(a.min())
print('')

print(a.argmin())
print('')

print(a.argmax())
print('')

print(np.cos([0,np.pi,2*np.pi]))
print('')

print(np.exp([1,2,3])) #無理數e也稱為歐拉數，約為2.718281,e的x次方
print('')

print(np.sqrt([1,4,9,16]))
print('')

15

1.707825127659933

2.5

0

0

5

[ 1. -1.  1.]

[ 2.71828183  7.3890561  20.08553692]

[1. 2. 3. 4.]



In [50]:
import numpy as np
a = np.arange(15).reshape(3,5)
print(a)
print('')

print(a.sum(axis=0)) #垂直方向加總
print('')

print(a.sum(axis=1)) #水平方向加總
print('')

print(a.max(axis=0))
print('')

print(a.max(axis=1))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

[15 18 21 24 27]

[10 35 60]

[10 11 12 13 14]

[ 4  9 14]


In [51]:
#存檔
import numpy as np
a = np.random.randint(1,20,16).reshape(4,4) #1-2取16筆整數
print(a)
print('')

b = np.sort(a,axis=0) #垂直
print(b)
print('')

c = np.sort(b,axis=1) #水平排序
print(c)
print('')

np.save('c',c) #前面'c'是檔名
np.savetxt('c',c) #後面的是矩陣名稱

d = np.load('c.npy')
print(d)

[[14 11 14 15]
 [14 16 12 10]
 [ 1  2 11 18]
 [10 16  3  5]]

[[ 1  2  3  5]
 [10 11 11 10]
 [14 16 12 15]
 [14 16 14 18]]

[[ 1  2  3  5]
 [10 10 11 11]
 [12 14 15 16]
 [14 14 16 18]]

[[ 1  2  3  5]
 [10 10 11 11]
 [12 14 15 16]
 [14 14 16 18]]
