In [1]:
import numpy as np

In [2]:
weight = np.array([0.15,0.2,0.25,0.4])

In [3]:
type(weight)

numpy.ndarray

In [4]:
weight.shape #可看出是一維陣列，由四個元素組成

(4,)

# 四檔股票漲跌幅

In [5]:
stock_return = np.array([[0.003731,0.021066,-0.004854,0.006098,-0.00606],[-0.001838,0.001842,-0.016544,-0.003738,0.003752],[-0.003087,-0.000344,-0.033391,0.007123,0.004597],[-0.024112,0.011704,-0.029563,-0.01457,0.016129]])

In [7]:
stock_return

array([[ 0.003731,  0.021066, -0.004854,  0.006098, -0.00606 ],
       [-0.001838,  0.001842, -0.016544, -0.003738,  0.003752],
       [-0.003087, -0.000344, -0.033391,  0.007123,  0.004597],
       [-0.024112,  0.011704, -0.029563, -0.01457 ,  0.016129]])

In [8]:
stock_return.shape #4*5的二維矩陣

(4, 5)

●將串列轉為陣列

In [11]:
weight_list = [0.15,0.2,0.25,0.4]

In [13]:
weight_array = np.array(weight_list)
weight_array

array([0.15, 0.2 , 0.25, 0.4 ])

In [14]:
return_list = [ 0.003731,  0.021066, -0.004854,  0.006098, -0.00606 ,
       -0.001838,  0.001842, -0.016544, -0.003738,  0.003752,
       -0.003087, -0.000344, -0.033391,  0.007123,  0.004597,
       -0.024112,  0.011704, -0.029563, -0.01457 ,  0.016129]

In [37]:
return_array = np.array(return_list)
return_array

array([ 0.003731,  0.021066, -0.004854,  0.006098, -0.00606 , -0.001838,
        0.001842, -0.016544, -0.003738,  0.003752, -0.003087, -0.000344,
       -0.033391,  0.007123,  0.004597, -0.024112,  0.011704, -0.029563,
       -0.01457 ,  0.016129])

In [40]:
return_array = return_array.reshape(4,5)
return_array

array([[ 0.003731,  0.021066, -0.004854,  0.006098, -0.00606 ],
       [-0.001838,  0.001842, -0.016544, -0.003738,  0.003752],
       [-0.003087, -0.000344, -0.033391,  0.007123,  0.004597],
       [-0.024112,  0.011704, -0.029563, -0.01457 ,  0.016129]])

●ravel函數，將多維陣列降維至一維陣列

In [21]:
return_array1 = return_array.ravel()
return_array1

array([ 0.003731,  0.021066, -0.004854,  0.006098, -0.00606 , -0.001838,
        0.001842, -0.016544, -0.003738,  0.003752, -0.003087, -0.000344,
       -0.033391,  0.007123,  0.004597, -0.024112,  0.011704, -0.029563,
       -0.01457 ,  0.016129])

●ndim檢視陣列的維度

In [24]:
print(weight_array.ndim)
print(return_array.ndim)

1
2


●size檢視陣列的元素數量

In [26]:
print(weight_array.size)
print(return_array.size)

4
20


In [ ]:
●dtype檢視陣列的元素型態

In [27]:
print(weight_array.dtype)
print(return_array.dtype)

float64
float64


# 陣列的產生
range產生串列
arange產生陣列

In [29]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
b = np.arange(1,15,3) #1-15之間，間隔3
b

array([ 1,  4,  7, 10, 13])

●產生等差序列

In [31]:
np.linspace(0,100,51) #0-100且個數為51的等差序列

array([  0.,   2.,   4.,   6.,   8.,  10.,  12.,  14.,  16.,  18.,  20.,
        22.,  24.,  26.,  28.,  30.,  32.,  34.,  36.,  38.,  40.,  42.,
        44.,  46.,  48.,  50.,  52.,  54.,  56.,  58.,  60.,  62.,  64.,
        66.,  68.,  70.,  72.,  74.,  76.,  78.,  80.,  82.,  84.,  86.,
        88.,  90.,  92.,  94.,  96.,  98., 100.])

●零陣列ones   ●元素一的陣列ones

In [32]:
#一維
zero_array1 = np.zeros(5)
zero_array1

array([0., 0., 0., 0., 0.])

In [33]:
#二維3*4
zero_array2 = np.zeros((3,4))
zero_array2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [34]:
#產生與原有陣列相同的維度的零陣列
zero_weight = np.zeros_like(weight_array)
print(zero_weight)
zero_return = np.zeros_like(return_array)
print(zero_return)

[0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


●建立單位矩陣(對角線上是1其餘為0的陣列)-eye

In [80]:
I = np.eye(5)
I

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# 陣列的索引、切片與排序

In [43]:
#索引
print(return_array[1,2])
#切片
print(return_array[2:,1:2])
# return_array
print(return_array[1])

-0.016544
[[-0.000344]
 [ 0.011704]]
[-0.001838  0.001842 -0.016544 -0.003738  0.003752]


In [45]:
#排序 axis=1為預設，依照一個[]排序，axis=0 ↓ 行大小排序
print(np.sort(return_array,axis=0))
print('')
print(np.sort(return_array,axis=1))
print('')
print(np.sort(return_array))

[[-0.024112 -0.000344 -0.033391 -0.01457  -0.00606 ]
 [-0.003087  0.001842 -0.029563 -0.003738  0.003752]
 [-0.001838  0.011704 -0.016544  0.006098  0.004597]
 [ 0.003731  0.021066 -0.004854  0.007123  0.016129]]

[[-0.00606  -0.004854  0.003731  0.006098  0.021066]
 [-0.016544 -0.003738 -0.001838  0.001842  0.003752]
 [-0.033391 -0.003087 -0.000344  0.004597  0.007123]
 [-0.029563 -0.024112 -0.01457   0.011704  0.016129]]

[[-0.00606  -0.004854  0.003731  0.006098  0.021066]
 [-0.016544 -0.003738 -0.001838  0.001842  0.003752]
 [-0.033391 -0.003087 -0.000344  0.004597  0.007123]
 [-0.029563 -0.024112 -0.01457   0.011704  0.016129]]


# 陣列的相關運算

●求和

In [46]:
return_array.sum(axis=0) #按日算股票的報酬

array([-0.025306,  0.034268, -0.084352, -0.005087,  0.018418])

In [47]:
return_array.sum(axis=1) #分別計算五檔五天的報酬

array([ 0.019981, -0.016526, -0.025102, -0.040412])

In [48]:
return_array.sum() #全部元素的總和

-0.062059

●求乘積prod

In [49]:
return_array.prod(axis=0)

array([-5.10435205e-10, -1.56230010e-10,  7.92717092e-08,  2.36564304e-09,
       -1.68584406e-09])

In [50]:
return_array.prod(axis=1)

array([ 1.40983129e-11, -7.85557141e-13, -1.16107947e-12, -1.96057312e-09])

In [51]:
return_array.prod()

-2.521099098076826e-44

●求最值(max/min)

In [52]:
return_array.max(axis=0) #按行

array([ 0.003731,  0.021066, -0.004854,  0.007123,  0.016129])

In [53]:
return_array.max(axis=1) #按列

array([0.021066, 0.003752, 0.007123, 0.016129])

In [54]:
return_array.max()#全部元素最大

0.021066

In [55]:
return_array.min(axis=0)

array([-0.024112, -0.000344, -0.033391, -0.01457 , -0.00606 ])

In [56]:
return_array.min(axis=1)

array([-0.00606 , -0.016544, -0.033391, -0.029563])

In [57]:
return_array.min()

-0.033391

●求平均值mean ●求變異數var標準差std

●開根號sqrt ●平方square ●exp以e為底的指數次方

In [58]:
np.sqrt(return_array) #負數無法開根號，故顯示為nan

d:\anaconda3\envs\anaconda_project\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([[0.06108191, 0.14514131,        nan, 0.07808969,        nan],
       [       nan, 0.04291853,        nan,        nan, 0.06125357],
       [       nan,        nan,        nan, 0.08439787, 0.06780118],
       [       nan, 0.10818503,        nan,        nan, 0.127     ]])

In [59]:
np.square(return_array)

array([[1.39203610e-05, 4.43776356e-04, 2.35613160e-05, 3.71856040e-05,
        3.67236000e-05],
       [3.37824400e-06, 3.39296400e-06, 2.73703936e-04, 1.39726440e-05,
        1.40775040e-05],
       [9.52956900e-06, 1.18336000e-07, 1.11495888e-03, 5.07371290e-05,
        2.11324090e-05],
       [5.81388544e-04, 1.36983616e-04, 8.73970969e-04, 2.12284900e-04,
        2.60144641e-04]])

In [60]:
np.exp(return_array)

array([[1.00373797, 1.02128945, 0.99515776, 1.00611663, 0.99395832],
       [0.99816369, 1.0018437 , 0.9835921 , 0.99626898, 1.00375905],
       [0.99691776, 0.99965606, 0.96716033, 1.00714843, 1.00460758],
       [0.97617637, 1.01177276, 0.97086971, 0.98553563, 1.01625977]])

●對數運算log log10  log2

●產生兩個陣列對應元素的最大值作為新的陣列

In [63]:
return_max = np.maximum(return_array,zero_return)
return_max

array([[0.003731, 0.021066, 0.      , 0.006098, 0.      ],
       [0.      , 0.001842, 0.      , 0.      , 0.003752],
       [0.      , 0.      , 0.      , 0.007123, 0.004597],
       [0.      , 0.011704, 0.      , 0.      , 0.016129]])

In [64]:
return_min = np.minimum(return_array,zero_return)
return_min

array([[ 0.      ,  0.      , -0.004854,  0.      , -0.00606 ],
       [-0.001838,  0.      , -0.016544, -0.003738,  0.      ],
       [-0.003087, -0.000344, -0.033391,  0.      ,  0.      ],
       [-0.024112,  0.      , -0.029563, -0.01457 ,  0.      ]])

# 矩陣的運算

●相關係數corrcoef

In [65]:
corrcoef_return = np.corrcoef(return_array)
corrcoef_return

array([[1.        , 0.38215651, 0.36338676, 0.30254781],
       [0.38215651, 1.        , 0.89216018, 0.80740528],
       [0.36338676, 0.89216018, 1.        , 0.60483848],
       [0.30254781, 0.80740528, 0.60483848, 1.        ]])

In [66]:
#矩陣的對角線
np.diag(corrcoef_return)

array([1., 1., 1., 1.])

In [67]:
#矩陣的上三角
np.triu(corrcoef_return)

array([[1.        , 0.38215651, 0.36338676, 0.30254781],
       [0.        , 1.        , 0.89216018, 0.80740528],
       [0.        , 0.        , 1.        , 0.60483848],
       [0.        , 0.        , 0.        , 1.        ]])

In [68]:
#矩陣的下三角
np.tril(corrcoef_return)

array([[1.        , 0.        , 0.        , 0.        ],
       [0.38215651, 1.        , 0.        , 0.        ],
       [0.36338676, 0.89216018, 1.        , 0.        ],
       [0.30254781, 0.80740528, 0.60483848, 1.        ]])

In [71]:
#矩陣轉置
print(return_array)
print(np.transpose(return_array))

[[ 0.003731  0.021066 -0.004854  0.006098 -0.00606 ]
 [-0.001838  0.001842 -0.016544 -0.003738  0.003752]
 [-0.003087 -0.000344 -0.033391  0.007123  0.004597]
 [-0.024112  0.011704 -0.029563 -0.01457   0.016129]]
[[ 0.003731 -0.001838 -0.003087 -0.024112]
 [ 0.021066  0.001842 -0.000344  0.011704]
 [-0.004854 -0.016544 -0.033391 -0.029563]
 [ 0.006098 -0.003738  0.007123 -0.01457 ]
 [-0.00606   0.003752  0.004597  0.016129]]


In [72]:
weight_array

array([0.15, 0.2 , 0.25, 0.4 ])

In [73]:
return_array

array([[ 0.003731,  0.021066, -0.004854,  0.006098, -0.00606 ],
       [-0.001838,  0.001842, -0.016544, -0.003738,  0.003752],
       [-0.003087, -0.000344, -0.033391,  0.007123,  0.004597],
       [-0.024112,  0.011704, -0.029563, -0.01457 ,  0.016129]])

In [75]:
#內積
average_return = np.dot(weight_array,return_array)
average_return

array([-0.0102245 ,  0.0081239 , -0.02420985, -0.00388015,  0.00744225])

●套件linalg用於線性代數運算

In [76]:
import numpy.linalg as la

In [77]:
la.det(corrcoef_return)

0.04911303905058602

●random有許多分布可參考官網https://docs.scipy.org/doc/numpy-1.15.0/reference/routines.random.html

In [82]:
import numpy.random as npr

In [84]:
#從正態(normal distribution)分配 取平均數1標準差2次數一萬次
x_norm = npr.normal(loc=1.0,scale=2.0,size=10000)
print('從正態分布中抽取的平均值',x_norm.mean())
print('從正態分布中抽取的標準差',x_norm.std())

從正態分布中抽取的平均值 1.0021906357279835
從正態分布中抽取的標準差 1.9977082591773285
